"""
Module that contains multiple functions used across mia_processes

:Contains:
    :Functions:
        - recupCover
"""

##########################################################################
# Populse_mia - Copyright (C) IRMaGe/CEA, 2018
# Distributed under the terms of the CeCILL license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html
# for details.
##########################################################################

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from reportlab.platypus import Flowable
from os import listdir, system, makedirs, remove
from os.path import isdir, isfile
from datetime import datetime
from sys import exit
from shutil import copyfile
# import readline as readlineComp
# import rlcompleter, getpass
# import logging # autocomp debug logfile

class PageNumCanvas(canvas.Canvas):
    "For  add \"page number of total\" in each footer."

    def __init__(self, *args, **kwargs):
        "Constructor."
        canvas.Canvas.__init__(self, *args, **kwargs)
        self.pages = []

    def showPage(self):
        "On a page break, add information to the list."
        self.pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        "Add the page number to each page (page x of y)."
        page_count = len(self.pages)

        for page in self.pages:
            self.__dict__.update(page)
            self.draw_page_number(page_count)
            canvas.Canvas.showPage(self)

        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        "Add the page number."
        page = "Page %s of %s" % (self._pageNumber, page_count)
        self.setFont("Helvetica", 7)
        self.drawRightString(195*mm, 10*mm, page)

class ReportLine(Flowable):
    "Line flowable --- draws a line in a flowable"

    def __init__(self, width, height=0):
        Flowable.__init__(self)
        self.width = width
        self.height = height

    def __repr__(self):
        return "Line(w=%s)" % self.width

    def draw(self):
        "draw the line"
        self.canv.line(0, self.height, self.width, self.height)


def recupCover(afile):
    """ Set up the coverage data for the report generated by MRIQC_report brick


    Read the \"afile\" file, split each line according to \":\"
    in a lx2 matrix.
    Then return the matrix ; column 0 = left from the colon ; column 1 = right
    from the colon.

    :param afile: A .txt file. Format == Parameter:Value.
    """

    styleSheet = getSampleStyleSheet()
    matrix = [[0, 0]]

    with open(afile, 'r') as txt:

        for line in txt:

            if bool(not line or line.isspace()):
                continue

            # Remove trailing characters
            line = line.rstrip()
            # Split the string according to the separator ":"
            header, doublePoint, info = line.partition(':')

            if matrix == [[0, 0]]:

                if header == " ":
                    matrix[0][0] = Paragraph("<para align=right>" + header +
                                             "</para>", styleSheet["Normal"])

                else:
                    # Class reportlab.platypus.paragraph.Paragraph
                    # with XML-like markup
                    matrix[0][0] = Paragraph("<para align=right><b>" + header +
                                             "&nbsp&nbsp&nbsp :</b></para>",
                                             styleSheet["BodyText"])
  
                matrix[0][1] = Paragraph("<para align=justify>" + info +
                                         "</para>", styleSheet["Normal"])

            else:

                if (header == " "):
                    temp = [Paragraph("<para align=right>" + header +
                                      "</para>", styleSheet["Normal"]),
                            Paragraph("<para align=justify>" + info +
                                      "</para>", styleSheet["Normal"])]

                else:
                    temp = [Paragraph("<para align=right><b>" + header +
                                      "&nbsp&nbsp&nbsp :</b></para>",
                                      styleSheet["BodyText"]),
                            Paragraph("<para align=justify>" + info +
                                      "</para>", styleSheet["Normal"])]

                matrix.append(temp)

    return matrix

def slice_planes_plot(img, slice_numb=25, inf_slice_start=281, slices_gap=5, cmap="Greys_r", out_dir=None):
    "blablabla"

